#------------------------------------------------------------------------------
# Terraform and Provider Configuration
#------------------------------------------------------------------------------
# This block defines the required Terraform version and the providers needed
# for this infrastructure setup.
# - AWS Provider: For managing AWS resources (VPC, EKS).
# - Helm Provider: For deploying Helm charts (Istio).
# - Kubernetes Provider: For interacting with the Kubernetes cluster.
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.39"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.9"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.20"
    }
  }

  required_version = ">= 1.2.0"
}

# Configures the AWS provider with the specified region.
provider "aws" {
  region = var.aws_region
}

# Configures the Kubernetes provider to connect to the created EKS cluster.
# It uses the cluster's endpoint, certificate authority data, and a token
# generated by the AWS CLI (`aws eks get-token`) for authentication.
# This allows Terraform to manage Kubernetes resources within the cluster.
provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
  }
}

# Configures the Helm provider to connect to the created EKS cluster.
# Similar to the Kubernetes provider, it uses the cluster's endpoint,
# certificate, and an AWS-generated token to authenticate.
# This enables Terraform to deploy Helm charts like Istio into the cluster.
provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
    }
  }
}
