{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "prime-calculator.fullname" . }}
spec:
  host: {{ include "prime-calculator.fullname" . }}
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "prime-calculator.fullname" . }}
spec:
  hosts:
  - "{{ .Values.istio.host }}"
  gateways:
  - {{ include "prime-calculator.fullname" . }}-gateway
  http:
  - route:
    {{- if and .Values.canary .Values.canary.enabled }}
    - destination:
        host: {{ include "prime-calculator.fullname" . }}
        subset: stable
        port:
          number: {{ .Values.service.port }}
      weight: 90
    - destination:
        host: {{ include "prime-calculator.fullname" . }}
        subset: canary
        port:
          number: {{ .Values.service.port }}
      weight: 10
    {{- else }}
    - destination:
        host: {{ include "prime-calculator.fullname" . }}
        subset: stable
        port:
          number: {{ .Values.service.port }}
      weight: 100
    {{- end }}
{{- end }}
