name: Release - Build and Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and push stable image
      uses: docker/build-push-action@v7
      with:
        context: ./app
        push: true
        tags: ghcr.io/${{ github.repository }}/istio-test-app:${{ steps.get_version.outputs.VERSION }}-stable
        build-args: |
          APP_VERSION=index.js

    - name: Build and push canary image
      uses: docker/build-push-action@v7
      with:
        context: ./app
        push: true
        tags: ghcr.io/${{ github.repository }}/istio-test-app:${{ steps.get_version.outputs.VERSION }}-canary
        build-args: |
          APP_VERSION=index.v2.js
